### ISSUE TITLE
Improved "en" translations

### ISSUE THREAD

**Issue by HybridVenom** [Stewart-Anubis/Toggle-Music-Sounds-Clientprefs-Anubis-Edition#1]
Changed wording, just a tiny improvement to an already great plugin :)

Improved translations can be found [here](https://github.com/Stewart-Anubis/Toggle-Music-Sounds-Clientprefs-Anubis-Edition/files/5648939/togglemusic_dhook.phrases.txt).

**Comment by Stewart-Anubis** [comment]
Thank you very much, then I will update the repository with your changes.

**Comment by HybridVenom** [comment]
Awesome to hear! :)
